export const PAGES = {
  MARKETING: "/marketing",
  LANDING: "/landing",
  SERVICES: "/services",
  CASE_STUDIES: "/case-studies",
  CASE_STUDY: "/case-study",
  BLOG_POSTS: "/blog-posts",
  BLOG_POST: "/blog-post",
  ABOUT: "/about",
  CONTACT: "/contact",
  TRAVEL: "/travel",
  TOURS: "/tours",
  TOUR: "/tour",
  CHECKOUT: "/checkout",
  CHECKOUT_COMPLETE: "/checkout-complete",
  CAREER: "/career",
  JOBS: "/jobs",
  JOB: "/job",
  COMING_SOON: "/coming-soon",
};
